AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploy single instance of Amazon linux using Jenkins"

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      AvailabilityZone: ap-southeast-2a
      ImageId: ami-0fb7513bcdc525c3b
      InstanceType: t2.micro
      SubnetId: subnet-01feb998410bd39b3
      SecurityGroupIds:
       - sg-0accba28318e4819c
      KeyName: DOI-POC-MOHAMMAD-ACCESS-KEY
      BlockDeviceMappings:
        -
          DeviceName: "/dev/xvda"
          Ebs:
            VolumeSize: 8
            VolumeType: gp2
      Tags:
        -
          Key: Name
          Value:  amapoc-moh-private-web-3
