AWSTemplateFormatVersion: '2010-09-09'
Description: VDC Centos 7 + helper scripts
Parameters:

  ImageId:
    Type: AWS::EC2::Image::Id
    Description: Instance AMI

  InstanceProfile:
    Description: Default instance profile
    Type: String
    Default: BTSManagedInstanceProfile
    ConstraintDescription: Must be BTSManagedInstanceProfile
    AllowedValues:
      - BTSManagedInstanceProfile

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName

  HostName:
    Type: String
    MaxLength: 15
    Default: amapocmoh-4
    Description: Name of the host

  SystemOwner:
    Type: String
    Description: Emails address of technical point of contact for the server.
    Default: ""

  OS:
    Type: String
    Description: Enter OS

  InstanceType:
    Description: EC2 instance types
    Type: String
    Default: t2.micro
    AllowedValues:
# General Purpose
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - t2.xlarge
      - t2.2xlarge
      - t3.nano
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.12xlarge
      - m5.24xlarge
# Compute Optimized
      - c5.large 
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
      - c5.9xlarge
      - c5.18xlarge 
# Memory Optimized
      - r5.large
      - r5.xlarge
      - r5.2xlarge
      - r5.4xlarge
      - r5.12xlarge
      - r5.24xlarge
    ConstraintDescription: must be a valid EC2 instance type.

  SecurityGroupIds:
    Description: Choose the default platform security group
    Type: AWS::EC2::SecurityGroup::Id

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Enter the SubnetId of the subnet
    ConstraintDescription: Must be a valid Subnet ID

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    CreationPolicy:
      ResourceSignal:
        Timeout: PT7M
        Count: '1'
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          full_install:
          - install_and_enable_cfn_hup
        install_and_enable_cfn_hup:
          files:
            "/etc/cfn/cfn-hup.conf":
              content:
                Fn::Join:
                - ""
                - - "[main]\n"
                  - stack=
                  - Ref: AWS::StackId
                  - "\n"
                  - region=
                  - Ref: AWS::Region
                  - "\n"
              mode: '000400'
              owner: root
              group: root
              
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
       - !Ref SecurityGroupIds
      KeyName: !Ref KeyName
      BlockDeviceMappings:
        -
          DeviceName: "/dev/sda1"
          Ebs:
            VolumeSize: 40
            VolumeType: gp2
      
      Tags:
        - Key: Name
          Value:  !Ref HostName

        - Key: SystemOwner
          Value: !Ref SystemOwner

        - Key: OS
          Value: !Ref OS

Outputs:
  EC2InstanceId:
    Description: Instance ID
    Value: !Ref MyEC2Instance
  EC2InstancePrivateIp:
    Description: Instance Private IP address
    Value: !GetAtt MyEC2Instance.PrivateIp