AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploy single instance of Amazon linux using Jenkins"

Parameters: 
  ImageId: 
    Type: AWS::EC2::Image::Id
    Description: AMI ID
  SubnetId: 
    Type: AWS::EC2::Subnet::Id
    Description: Subnet ID

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref ImageId
      InstanceType: t2.micro
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
       - sg-0accba28318e4819c
      KeyName: DOI-POC-MOHAMMAD-ACCESS-KEY
      BlockDeviceMappings:
        -
          DeviceName: "/dev/xvda"
          Ebs:
            VolumeSize: 8
            VolumeType: gp2
      Tags:
        -
          Key: Name
          Value:  amapoc-moh-private-web-3